/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/eRSt24KchFs
 */
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function Component2() {
  return (
    <main className="p-5">
      <h1 className="text-4xl font-bold mb-5">Student Gradebook</h1>
      <div className="grid gap-5">
        <Card className="bg-[#ffffff] shadow-md rounded-md">
          <CardHeader className="p-4 border-b border-gray-200">
            <CardTitle className="text-xl font-semibold">Data Entry: John Doe</CardTitle>
            <p className="text-sm text-gray-500">ID: 1234</p>
            <p className="text-sm text-gray-500">Subject: Math</p>
          </CardHeader>
          <CardContent className="p-4">
            <form>
              <label className="block mb-2 text-sm text-gray-600">Grade</label>
              <input className="mb-4 px-3 py-2 border rounded w-full" type="text" />
              <Button className="px-4 py-2 bg-blue-500 text-white rounded">Submit</Button>
            </form>
          </CardContent>
        </Card>
        <Card className="bg-[#ffffff] shadow-md rounded-md">
          <CardHeader className="p-4 border-b border-gray-200">
            <CardTitle className="text-xl font-semibold">Data Entry: Jane Smith</CardTitle>
            <p className="text-sm text-gray-500">ID: 2345</p>
            <p className="text-sm text-gray-500">Subject: English</p>
          </CardHeader>
          <CardContent className="p-4">
            <form>
              <label className="block mb-2 text-sm text-gray-600">Grade</label>
              <input className="mb-4 px-3 py-2 border rounded w-full" type="text" />
              <Button className="px-4 py-2 bg-blue-500 text-white rounded">Submit</Button>
            </form>
          </CardContent>
        </Card>
        <Card className="bg-[#ffffff] shadow-md rounded-md">
          <CardHeader className="p-4 border-b border-gray-200">
            <CardTitle className="text-xl font-semibold">Data Entry: Emma Williams</CardTitle>
            <p className="text-sm text-gray-500">ID: 3456</p>
            <p className="text-sm text-gray-500">Subject: Science</p>
          </CardHeader>
          <CardContent className="p-4">
            <form>
              <label className="block mb-2 text-sm text-gray-600">Grade</label>
              <input className="mb-4 px-3 py-2 border rounded w-full" type="text" />
              <Button className="px-4 py-2 bg-blue-500 text-white rounded">Submit</Button>
            </form>
          </CardContent>
        </Card>
      </div>
    </main>
  )
}
