/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/zXG9dTbrVUx
 */
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import CourseCard from "@/components/courseCard"

export function Component() {
  return (
    <main className="p-5 w-1/2">
      <div className="grid gap-5">
        <CourseCard/>
        <CourseCard/>
        <CourseCard/>
        <CourseCard/>

      </div>
    </main>
  )
}
